// webpack-react-app/src/App.js
import React, { useState, useEffect } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

let a

function App({ onGlobalStateChange, setGlobalState }) {
  const [count, setCount] = useState(0)
  const [mainCount] = useMainAppState(onGlobalStateChange)


  const onCountButtonClick = () => {
    setCount((count) => count + 1)
    setGlobalState?.({ reactCount: count + 1 })
  }

  return (
    <>
      <div>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo sigle-react-logo" alt="React logo" />
        </a>
      </div>
      <h1>Webpack 5 + React 18</h1>
      <div className="card">
        <button onClick={onCountButtonClick}>
          count is {count}
        </button>
        {typeof mainCount === 'number' ? <p> Main app count is <b>{mainCount}</b></p> : null}
        <p>
          Edit <code>src/App.js</code> and save to test HMR
        </p>
      </div>
    </>
  )
}

function useMainAppState(onGlobalStateChange) {
  const [mainCount, setMainCount] = useState(window.__POWERED_BY_QIANKUN__ ? 0 : undefined)

  useEffect(() => {
    if (typeof onGlobalStateChange === "function") {
      onGlobalStateChange((state, prev) => {
        // state: 变更后的状态; prev 变更前的状态
        console.log("[react]onGlobalStateChange:" + state.count)
        setMainCount(state.count)
      })
    }
  }, [])
  return [mainCount]
}


export default App

// vite-vue-app/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import { ref, onMounted } from 'vue'

const props = defineProps<{ onGlobalStateChange: Function }>()
const otherCount = ref(0)

onMounted(() => {
  if (typeof props.onGlobalStateChange === "function") {
      props.onGlobalStateChange((state:{[key:string]: any}) => {
        // state: 变更后的状态; prev 变更前的状态
        console.log("[vue] onGlobalStateChange:" + state.reactCount)
        otherCount.value = state.reactCount
      })
    }
})

</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite 4 + Vue 3" :otherCount="otherCount"/>
</template>

<style scoped>
.logo {
  height: 3em;
  padding: 1em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
